CREATE TABLE `TEST`.`ENGLISH`
(
    ENGLISH_SEQ_NO INT NOT NULL AUTO_INCREMENT,
    ENGLISH_TEXT VARCHAR(100) NOT NULL,
    KOREAN_TEXT VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TEST PRIMARY KEY(ENGLISH_SEQ_NO)
);


ALTER TABLE TEST.ENGLISH_TEXT COMMENT '영문장';
ALTER TABLE TEST.KOREAN_TEXT COMMENT '한국어 해석';