version: "3.3"
services:
  mysql:
    container_name: dbsync-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    image: demo/mysql:5.7
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=TEST
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
  mongodb:
    container_name: dbsync-mongodb
    build:
      context: ./mongodb/
      dockerfile: Dockerfile
    image: demo/mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=TEST
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27018:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    container_name: kafka-connect
    image: debezium/connect
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses